### PR TITLE
5. View a separate page for each category with a list of related reviews

### PR DESCRIPTION
**Pull request by Lauren135**
5. View a separate page for each category with a list of related reviews

### CODE REVIEW

**Review by Angaca — CHANGES_REQUESTED** [review]
Functionality is fine, but even if this is just a draft of the final design it needs a minimum of adjustments. The single review overflows the page on the sides and cannot be read on the left side. Moreover, I would try to find a different solution than such an extensive and lengthy drop-down menu for the categories, what about a different page if you really want to include the explanations of them or just move the explanations inside the page after you click the category. The last thing, the single category should be uppercased in your navigation/drop-down menu for a smoother experience

**Review by HeatherEver — CHANGES_REQUESTED** [review]
The functionality is good but when a category is selected in the dropdown menu the URL is not changing to reflect this. There is something called React Navigate that can help here to change the URL path when something is selected, have a look into that if you would like to keep the dropdown menu. ⭐

**Comment by douglashellowell** [comment]
There's a bug in your code! 🐛

Clicking `All Reviews` throws a 
```
setSelectedCategory is not a function
```
error!

--- 

Apart from that it's all working great!

Fix this bug and feel free to merge

**Comment by douglashellowell** [comment]
Nice one! ready to merge 🚀

**Pull request merged**
